### ISSUE TITLE
buildURL in adapter is too magical

### ISSUE THREAD

**Issue by bobholt** [endpoints/ember-data-endpoints#6]
Based on discussion in #1 I really think we should remove the magic of buildURL in the adapter. I would consent to everything else about the type inference if we could do that.

`buildURL` is trying to guess what includes to add to a `store.find` request, but that forces us into naming conventions within Ember models that neither @cowboy or I seem to much care for.

It's much more palatable for me to explicitly add the include to any store.find I need to do. It makes it crystal clear in the code what each request is actually bringing along, we don't run into an issue where inadvertently not marking something async brings a ton of data down on us, and we can name our relation references inside our Ember models to be whatever we want.

**Comment by tkellen** [comment]
:+1: from me, this is good resolution for #1

**Comment by tkellen** [comment]
@bmac, if you're good with this, could you merge?
